blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls')),
    path('profile/',include('user_profile.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/post/urls.py
from django.urls import path
from . import views

app_name='post'

urlpatterns=[
    path('',views.home,name='home'),
    path('addpost',views.add_post,name='add_post'),
    path('tag_post/<str:tag>',views.tag_post,name='tag_post'),
    path('login',views.log_in,name='log_in'),
    path('signup',views.sign_up,name='sign_up'),
    path('logout',views.log_out,name='log_out'),
    path('allposts',views.all_post,name='all_post'),
    path('post_detail/<int:p_id>',views.post_detail,name='detail'),
    path('like/<int:p_id>',views.like,name='like'),
    

]

blog/user_profile/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name='user_profile'

urlpatterns = [
    path('', views.view_profile, name='view_profile'),
    path('reg/', views.view_reg, name='view_reg'),
    path('logout/',LogoutView.as_view(),name='logout')
]

blog/post/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone



# Create your models here.
class Post(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    p_title = models.CharField(max_length=200)
    p_desc = models.TextField() 
    file = models.FileField(upload_to='files/') 
    tag = models.CharField(max_length=50, default="Others")
    likes= models.ManyToManyField(User,related_name='likes',blank=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.p_title

    def total_likes(self):
        return self.likes.count()

blog/user_profile/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    # GENDER_CHOICES=(
    #     ('M','Male'),
    #     ('F','Female'),
    # )
    user_name=models.ForeignKey(User,  on_delete=models.CASCADE)
    bio=models.TextField()
    interests=models.TextField()
    phone=models.CharField('Contact Phone', max_length=20)
    # gender=models.CharField(max_length=1,choices=GENDER_CHOICES)
    age=models.IntegerField()
    image = models.FileField(upload_to='myfiles/', null=True, blank=True) 
    user_created_on=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user_name.username

blog/post/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username', 'email','password']

  
class PostForm(forms.ModelForm): 
    
    class Meta: 
        model = Post
        fields = ['p_title','p_desc','file','tag'] 

blog/user_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class UserForm(forms.ModelForm):
    
    class Meta:
        model=Profile
        fields=['phone','age','bio','interests','image']

  

blog/post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .forms import UserForm, PostForm
from .models import Post

# Create your views here.
def home(request):
    p=Post.objects.all().order_by('-date')
    t=Post.objects.values('tag').distinct() 
    return render(request,'post/homepage.html',{'p':p,'t':t})

def sign_up(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('profile/reg')
    return render(request, 'post/sign_up.html',{'form':form})

def add_post(request):
    if request.method == 'POST': 
        form = PostForm(request.POST, request.FILES) 
        if form.is_valid(): 
            post=form.save(commit=False)
            post.user=request.user
            post.save() 
            return redirect('/')
        else:
            return HttpResponse("<h1>Fail</h1>")
    else: 
        form = PostForm() 
    return render(request, 'post/add_post.html', {'form' : form}) 

def log_in(request):
    if request.method == 'POST':
        username= request.POST['username']
        password= request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'post/log_in.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'post/log_in.html', {'error_message': 'Enter correct username or password'})
    return render(request, 'post/log_in.html')

def log_out(request):
    logout(request)
    form = UserForm(request.POST or None)
    return render(request, 'post/log_in.html',{'form':form})


def all_post(request):
    p=Post.objects.all().order_by('-date')
    t=Post.objects.values('tag').distinct()  
    return render(request,'post/allpost.html',{'t':t,'p':p})

def tag_post(request,tag):
    tag=str(tag)
    p=Post.objects.filter(tag=tag)
    return render(request,'post/tag_post.html',{'p':p,'tag':tag})


def post_detail(request,p_id):
    p_id=int(p_id)
    p=Post.objects.get(id=p_id)
    is_liked=False
    if p.likes.filter(id=request.user.id).exists():
        is_liked=True
    return render(request,'post/post_detail.html',{'p':p,'is_liked':is_liked,'total_likes':p.total_likes()})

def like(request,p_id):
    p=get_object_or_404(Post,id=request.POST.get('post_id'))
    is_liked=False
    if p.likes.filter(id=request.user.id).exists():
        p.likes.remove(request.user)
        is_liked=False
    else:
        p.likes.add(request.user)
        is_liked=True
    p_id=int(p_id)
    p=Post.objects.get(id=p_id)
    return render(request,'post/post_detail.html',{'p':p,'is_liked':is_liked,'total_likes':p.total_likes()})

blog/user_profile/views.py
from django.shortcuts import render
from .models import Profile
from .forms import UserForm
from django.http import HttpResponse
from django.shortcuts import redirect
# Create your views here.

def view_profile(request):
    profile = Profile.objects.get(user_name=request.user)
    return render(request, 'user_profile/view_profile.html', {'profile':profile})

def view_reg(request):
    if request.method == 'POST': 
        form = UserForm(request.POST, request.FILES)
        if form.is_valid(): 
            post=form.save(commit=False)
            post.user_name=request.user
            post.save() 
            return redirect('/')
        else:
            return HttpResponse("<h1>Fail</h1>")
    else: 
        form = UserForm() 
    return render(request,'user_profile/reg.html',{'form':form})

blog/post/templates/nav.html
{% load staticfiles %}

<head>
    <title>{% block title %}Blog{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<link href="https://fonts.googleapis.com/css?family=Engagement&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Grenze&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cookie|Lobster+Two&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Amaranth&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Neuton&display=swap" rel="stylesheet">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'post/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'post/posts.css' %}" />


<!--navigation_bar-->
<nav class="navbar navbar-inverse" id="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="{%url 'post:home' %}" style="color: white;font-size: 60px;margin-top: 10px;">Blog</a>
        </div>
        <!--links-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-right" id="navlist">
                <li><a href="{% url 'post:all_post'%}" style="color: white">&nbsp;All posts</a></li>
                <li><a href='#' style="color: white">&nbsp;About us</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'user_profile:view_profile'%}" style="color: white">&nbsp;Profile</a></li>
                <li><a href="{% url 'user_profile:logout'%}" style="color: white">&nbsp;Logout</a></li>
                {% else %}
                <li><a href="{% url 'post:log_in'%}" style="color: white">&nbsp;Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


<body>
{% block body %}
{% endblock %}

  

</body>

blog/post/templates/post/add_post.html
{% extends 'nav.html'%}
{% block title%}Add Post{% endblock %}

{% block body %}
<body id="addpost">
        <script type="text/javascript"> 
            var tags = [  
            "Adventure", 
            "Music", 
            "Coding", 
            "Food", 
            "Sports", 
            "Books", 
            "Travel", 
            "Hangout",
            "Anime",
            "Dance" 
              ]; 
          
              /*list of available options*/ 
             var n= tags.length; //length of datalist tags     
          
             function ac(value) { 
                document.getElementById('datalist').innerHTML = ''; 
                 //setting datalist empty at the start of function 
                 //if we skip this step, same name will be repeated 
                   
                 l=value.length; 
                 //input query length 
             for (var i = 0; i<n; i++) { 
                 if(((tags[i].toLowerCase()).indexOf(value.toLowerCase()))>-1) 
                 { 
                     //comparing if input string is existing in tags[i] string 
          
                     var node = document.createElement("option"); 
                     var val = document.createTextNode(tags[i]); 
                      node.appendChild(val); 
          
                       document.getElementById("datalist").appendChild(node); 
                           //creating and appending new elements in data list 
                     } 
                 } 
             } 
           
        </script> 

<div class="addpost">
    <div class="container">
            <form method="POST" action="{% url 'post:add_post'%}"  enctype="multipart/form-data">
                {% csrf_token %} 
                <h1 id="add_h1">Create Post</h1><br>
                <label>Title:</label><br><input type="text" name="p_title" required><br>
                <label>Content:</label><br><textarea name="p_desc" required></textarea><br><br>
                <label>Image:</label><br><input type="file" style="font-family: 'Playfair Display', serif; font-size:18px" name="file" required><br>
                <label>Tag:</label><br><input type="text" name="tag" autocomplete="off" list="datalist" onkeyup="ac(this.value)">
                <datalist id="datalist"> 
                        <option value="Adventure"></option> 
                        <option value="Music"></option> 
                        <option value="Coding"></option> 
                        <option value="Food"></option> 
                        <option value="Sports"></option> 
                        <option value="Books"></option> 
                        <option value="Travel"></option> 
                        <option value="Hangout"></option> 
                        <option value="Anime"></option> 
                        <option value="Dance"></option> 
                        </datalist><br>
                <button type="submit" style="font-family: 'Playfair Display', serif; font-size:20px">Post</button>
            </form>
        
    </div>
</div>


{% endblock %}

blog/post/templates/post/allpost.html
{% extends 'nav.html'%}

{% block body %}

<body>
<script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();   
        });
</script>
    
<div class="container-fluid">

<div class="post">
        <p style="font-family: 'Cookie', cursive;font-size: 50px;margin: 5px 25px">Search using tags...</p>
        {% for t in t%}
        <a href="{% url 'post:tag_post' t.tag%}" class="btn"><h2 style="font-family: 'Playfair Display', serif; font-size:25px; margin-left: 25%;">{{t.tag|truncatechars:9 }}</h2></a>
        {% endfor %}
</div>
<div>
        <h1 style="font-family: 'Cookie', cursive;font-size: 50px;margin: 5px 25px">Posts</h1>
        {% for p in p %}
        <div class="col-lg-6"  id="allpost">
                <div class="col-lg-6" style="padding: 0">
                        <a href="{% url 'post:detail' p.id %}" style="text-decoration: none;"><img src="{{p.file.url}}" id="allpost_img" ></a>
                </div>

                <div class="col-lg-6" id="content">
                        <h4 style="font-family: 'Grenze', serif;font-size:28px">{{p.p_title}}</h4>
                        <a href="{% url 'post:tag_post' p.tag%}" style="text-decoration: none;"><p style="color:rgb(161, 156, 156); font-size: 22px; font-family: 'Bree Serif', serif;">#{{p.tag}}</p></a>
                        <div style="width: 300px;">
                                <p style="font-family: 'Amaranth', sans-serif;font-size:20px">{{p.p_desc|truncatewords:20}}</p>
                        </div>
                        <a href="{% url 'post:detail' p.id %}" style="color:rgb(255, 100, 38); font-size: 22px; font-family: 'Bree Serif', serif;">Read more<span class="glyphicon glyphicon-chevron-right" style="font-size: 16px;"></span></a><br><br>       
                </div>
        </div>
        {% endfor %}<br>
        {% if user.is_authenticated %}
                <a href="{% url 'post:add_post'%}" class="btn btn-info btn-lg pen" id="pen"><span class="glyphicon glyphicon-pencil" id="pencil"></span></a>
        {% else %}
                <a href="#" class="btn btn-info btn-lg pen" id="pen"><div data-toggle="tooltip" data-html="true" title="<p style='font-size:16px'><b>Login to create post</b></p>"><span class="glyphicon glyphicon-pencil" id="pencil"></span></div></a>
        {% endif %}  
</div>
</div>
</body>
<!-- Site footer -->
<footer class="site-footer" >
        <div class="container" >
                <div class="row" style="font-size: 16px; font-family: 'Bree Serif', serif;">
                        <div class="col-sm-12 col-md-6">
                                <h6>About</h6>
                                <p>Blog is a site where one can discover new things and share their own lifestyle with others. They can share posts & images of any category. Through this, one can view his ideas & messages to the world and can get to know what others think about their post.</p>
                        </div>
                        <div class="col-lg-6 col-md-12" style="padding: 1% 20%;">
                                <h6><a href="#" style="color: white;">Contact us</a></h6><br>
                                <h6><a href="#" style="color: white;">About us</h6>
                        </div>
                </div>
        </div>
  </footer>
{% endblock %}

blog/post/templates/post/homepage.html
{% extends 'nav.html'%}

{% block body %}
<body>   
<script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();   
    });
</script>

<div>
    <div class="col-lg-6" style="padding: 1% 2%;font-family: 'Neuton', serif;">
        <h2>Do you have a curiousity to get to know something new and different....</h2>
        <h2>Do you love to write about your life....</h2><br>
        <h2>Then <span style="color: #2F2FA2 ; font-size: 40px">"Blog"</span> is the right place for you</h2>
    </div>
    <div class="col-lg-6">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRFehdRJB5DQtgptuLCBp7tDAbkpCgoA9RbSYL2IIeqDSdfzlqs" style="width: 650px;">
    </div>

<section>
    <div class="container" id="post"> 
            <div class="col-lg-6 col-md-12">
                <h1 style="font-family: 'Playfair Display', serif; font-size:40px;">Recent Posts</h1><br>
                    {% for p in p|slice:"4" %}
                   <div class="col-lg-6" id="recent">
                        <div class="row">
                            <div id="recent_div"><a href="{% url 'post:detail' p.id %}" style="text-decoration: none;"><img src="{{p.file.url}}" id="recent_img"></a><br></div>
                            <a href="{% url 'post:tag_post' p.tag%}" style="text-decoration: none;"><p style="color:rgb(161, 156, 156); font-size: 22px; font-family: 'Bree Serif', serif;">#{{p.tag}}</p></a>
                            <h4 style="font-family: 'Grenze', serif;font-size:26px">{{p.p_title}}</h4>
                            <a href="{% url 'post:detail' p.id %}" style="color:rgb(255, 100, 38); font-size: 24px; font-family: 'Bree Serif', serif;">Read more<span class="glyphicon glyphicon-chevron-right" style="font-size: 16px;"></span></a><br><br>
                        </div>
                    </div>
                    {% endfor %}
            </div>

            <div class="col-lg-6 col-md-12" id="tag_img" >
                <div class='wrapper'>
                        <img src='https://i.pinimg.com/564x/26/64/ed/2664ed9a7129fef9369f5fcf24a9d9fe.jpg' />
                        <div class='description'>
                            <h4 class='description_content'>Tags</h4>
                            {% for t in t|slice:"4" %}
                            <a href="{% url 'post:tag_post' t.tag%}" style="text-decoration: none;"><p id="p">{{t.tag}}</p></a>
                            {% endfor %}
                            <p>and many more...</p>
                        </div>
                    </div>
            </div>
    </div>
</section>

{% if user.is_authenticated %}
    <a href="{% url 'post:add_post'%}" class="btn btn-info btn-lg pen" id="pen"><span class="glyphicon glyphicon-pencil" id="pencil"></span></a>
{% else %}
    <a href="#" class="btn btn-info btn-lg pen" id="pen"><div data-toggle="tooltip" data-html="true" title="<p style='font-size:16px'><b>Login to create post</b></p>"><span class="glyphicon glyphicon-pencil" id="pencil"></span></div></a>
{% endif %} 

</body>

<footer class="site-footer" >
    <div class="container" >
            <div class="row" style="font-size: 16px; font-family: 'Bree Serif', serif;">
                    <div class="col-sm-12 col-md-6">
                            <h6>About</h6>
                            <p>Blog is a site where one can discover new things and share their own lifestyle with others. They can share posts & images of any category. Through this, one can view his ideas & messages to the world and can get to know what others think about their post.</p>
                    </div>
                    <div class="col-lg-6 col-md-12" style="padding: 1% 20%;">
                            <h6><a href="#" style="color: white;">Contact us</a></h6><br>
                            <h6><a href="#" style="color: white;">About us</h6>
                    </div>
            </div>
    </div>
</footer>
{% endblock %}

blog/post/templates/post/log_in.html
{% extends 'nav.html'%}
{% block title%}Login{% endblock %}

{% block body %}
<body id="login">
<div class="box">
    <div class="container" id="reg">
        <div class="row">
            <form method="POST" action="{% url 'post:log_in'%}" class="login">
                {% csrf_token %}
                <h1 id="login_h1">Login</h1>
                {% if error_message %}
                <p style="color:white; text-align: center;"><strong>{{ error_message }}</strong></p>
                {% endif %}
                <input type="text" name="username" placeholder="Username"/><br>
                <input type="password" name='password' placeholder="Password"/><br>
                <input type='submit' value="Submit"/><br>
                <p id="log_p">Don't have an account? <a href="{% url 'post:sign_up'%}">Signup</a></p>
            </form>
        </div>
    </div>
</div>
</body>



{% endblock %}

blog/post/templates/post/post_detail.html
{% extends 'nav.html'%}

{% block body %}
<script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();   
        });
</script>

<body>  
  
  <div>
    <h1 style="font-family: 'Grenze', serif;font-size: 70px; text-align: center;">{{p.p_title}}</h1>
    <p style="font-size: 35px;margin:0 70% ;">-&nbsp;<a href="#">{{p.user}}</a></p>
  </div><br>
    
    <div class="container">
        <div class="col-lg-12">
                <img src="{{p.file.url}}" id="detail_img">
                <div class="col-lg-6">
                        <a href="{% url 'post:tag_post' p.tag%}" style="text-decoration: none;"><p style="color:rgb(161, 156, 156); font-size: 22px; font-family: 'Bree Serif', serif;margin: 1% 38%;">#{{p.tag}}</p></a>
                </div>
                <div class="col-lg-6">
                <form action="{% url 'post:like' p.id%}" method="POST">
                    {% csrf_token %}
                    {% if is_liked %}
                    <button type="submit" name="post_id" value="{{p.id}}" style="margin:2% 45% " style="background-color: crimson;">Dislike</button>
                    {% else %}
                        {% if user.is_authenticated %}
                        <button type="submit" name="post_id" value="{{p.id}}" style="margin:2% 45% " style="background-color: cornflowerblue;">Like</button>
                        {% else %}
                        <div data-toggle="tooltip" data-html="true" title="<p style='font-size:16px'><b>Login to like the post</b></p>"><a href="#"><input type="button" name="post_id" value="Like" style="margin:2% 45% "></a></div>
                        {% endif %}
                    {% endif %}
                    <p style="margin:1% 45%">{{total_likes}}&nbsp;Likes</p>
                  </form>
                  </div>
        </div>

        <div class="col-lg-12"><br>
                <p style="font-family: 'Amaranth', sans-serif;font-size:20px">{{p.p_desc}}</p><br>
        </div>
      </div>
</div>

{% if user.is_authenticated %}
    <a href="{% url 'post:add_post'%}" class="btn btn-info btn-lg pen" id="pen"><span class="glyphicon glyphicon-pencil" id="pencil"></span></a>
{% else %}
    <a href="#" class="btn btn-info btn-lg pen" id="pen"><div data-toggle="tooltip" data-html="true" title="<p style='font-size:16px'><b>Login to create post</b></p>"><span class="glyphicon glyphicon-pencil" id="pencil"></span></div></a>
{% endif %} 

<footer class="site-footer" >
  <div class="container" >
          <div class="row" style="font-size: 16px; font-family: 'Bree Serif', serif;">
                  <div class="col-sm-12 col-md-6">
                          <h6>About</h6>
                          <p>Blog is a site where one can discover new things and share their own lifestyle with others. They can share posts & images of any category. Through this, one can view his ideas & messages to the world and can get to know what others think about their post.</p>
                  </div>
                  <div class="col-lg-6 col-md-12" style="padding: 1% 20%;">
                          <h6><a href="#" style="color: white;">Contact us</a></h6><br>
                          <h6><a href="#" style="color: white;">About us</h6>
                  </div>
          </div>
  </div>
</footer>
{% endblock %}

blog/post/templates/post/sign_up.html
{% extends 'nav.html'%}
{% block title%}Signup{% endblock %}

{% block body %}
<body id="signup">
<div class="box">
<div class="container" id="reg">
        <div class="row">
        <form method="POST" class="signup" action="{% url 'post:sign_up'%}">
            {% csrf_token %}
            <h1 id="signup_h1">Signup</h1>
            <input type="text" name="username" placeholder="Username"/ required><br>
            <input type="email" name="email" placeholder="Email"/ required><br>
            <input type="password" name='password' placeholder="Password"/ required><br>
            <input type='submit' value="Submit"/><br>
        </form>
    </div>
</div>
</div>
</body>
{% endblock %}

blog/post/templates/post/tag_post.html
{% extends 'nav.html'%}

{% block body %}
<script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();   
        });
</script>


<body>
        <div class="container-fluid">
                <h2 style="font-family: 'Playfair Display', serif; font-size:40px; margin-left: 5%;">{{tag}}</h2><br>
                {% for p in p %}
                <div class="col-lg-3">
                <div class="card" style="width:100%">
                        <a href="{% url 'post:detail' p.id %}" style="text-decoration: none;"><img src="{{p.file.url}}" id="post_img"></a>
                        <div class="card_desc">
                                <p style="color:rgb(161, 156, 156); font-size: 22px; font-family: 'Bree Serif', serif;">#{{p.tag}}</p>
                                <h4 style="font-family: 'Grenze', serif;font-size:26px">{{p.p_title}}</h4>
                                <a href="{% url 'post:detail' p.id %}" style="color:rgb(255, 100, 38); font-size: 24px; font-family: 'Bree Serif', serif;">Read more<span class="glyphicon glyphicon-chevron-right" style="font-size: 16px;"></span></a><br><br>
                        </div>
                </div>
                </div>
                {% endfor %}
                {% if user.is_authenticated %}
                        <a href="{% url 'post:add_post'%}" class="btn btn-info btn-lg pen" id="pen"><span class="glyphicon glyphicon-pencil" id="pencil"></span></a>
                {% else %}
                        <a href="#" class="btn btn-info btn-lg pen" id="pen"><div data-toggle="tooltip" data-html="true" title="<p style='font-size:16px'><b>Login to create post</b></p>"><span class="glyphicon glyphicon-pencil" id="pencil"></span></div></a>
                {% endif %} 

        </div>

</body>
<footer class="site-footer" >
        <div class="container" >
                <div class="row" style="font-size: 16px; font-family: 'Bree Serif', serif;">
                        <div class="col-sm-12 col-md-6">
                                <h6>About</h6>
                                <p>Blog is a site where one can discover new things and share their own lifestyle with others. They can share posts & images of any category. Through this, one can view his ideas & messages to the world and can get to know what others think about their post.</p>
                        </div>
                        <div class="col-lg-6 col-md-12" style="padding: 1% 20%;">
                                <h6><a href="#" style="color: white;">Contact us</a></h6><br>
                                <h6><a href="#" style="color: white;">About us</h6>
                        </div>
                </div>
        </div>
  </footer>
{% endblock %}

blog/user_profile/templates/user_profile/reg.html
{% extends 'nav.html' %}

{% block body %}
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'user_profile/newstyle.css' %}">

<form action="{% url 'user_profile:view_reg' %}" method="post" name="main_form" enctype="multipart/form-data">
        {% csrf_token %}
    <h4><b><br>Registration Info</b></h4><br>
    {{form.as_p}}
    <input type="submit" value="Submit">
    </form>
  {% endblock %}

blog/user_profile/templates/user_profile/view_profile.html
{% extends 'nav.html' %}

{% block body %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'user_profile/style.css' %}">

<title>Profile</title>
<link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet" media="screen">

 
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
<link href='//fonts.googleapis.com/css?family=Lato:100,300' rel='stylesheet' type='text/css'>
<div class="container top50">

        <div class="row">
        	<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

                <div class="item-1">
                	<div class="img-container">
                    	<a href="#"><img src="{{profile.image.url}}" /></a>
                    </div>
                    <div class="robin-key">
                      <p>{{ profile.profile_name }}</p><br></div>
                      <div class="robin-key"><p>{{ profile.user_name.username }}</p><br></div>
                      <div class="robin-key"><p>Bio: {{ profile.bio }}</p><br></div>
                      <div class="robin-key"><p>Goals - Interests: {{ profile.interests }}</p><br></div>
                      <div class="robin-key"><p>Email: {{ profile.user_name.email }}</p><br></div>
                      <div class="robin-key"><p>Phone no: {{  profile.phone }}</p><br></div>                      
                      <div class="robin-key"><p>Age: {{ profile.age }}</p><br></div>

                
                </div>
            </div>
        </div>

    </div>
  {% endblock %}